-- SETUP DATABASE SIMPEL & PRAKTIS UNTUK MY BUSINESS POS
-- Run these commands in your Supabase SQL editor

-- 1. BERSIH-BERSIH TOTAL (RESET)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;

-- 2. BUAT TABEL PROFIL USER
CREATE TABLE user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT DEFAULT 'Staff',
  role TEXT NOT NULL DEFAULT 'cashier' CHECK (role IN ('owner', 'cashier')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 3. BUAT TABEL PRODUK
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  base_cost NUMERIC DEFAULT 0,
  target_profit NUMERIC DEFAULT 0,
  selling_price NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. BUAT TABEL PENJUALAN
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name TEXT,
  qty INT DEFAULT 1,
  gross_total NUMERIC DEFAULT 0,
  net_revenue NUMERIC DEFAULT 0,
  actual_profit NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. LOGIKA SAKTI (AUTO-ADMIN)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Cek: Kalau emailnya 'admin@tokoku.com', jadikan OWNER. Selain itu CASHIER.
  IF NEW.email = 'admin@tokoku.com' THEN
      INSERT INTO public.user_profiles (user_id, email, name, role)
      VALUES (NEW.id, NEW.email, 'Bos Besar', 'owner');
  ELSE
      INSERT INTO public.user_profiles (user_id, email, name, role)
      VALUES (NEW.id, NEW.email, 'Kasir', 'cashier');
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Pasang Trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. KEAMANAN (RLS) - AGAR DATA AMAN
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- ATURAN AKSES (POLICIES)
-- 1. Semua user login boleh BACA data produk & sales
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Public Read Sales" ON sales FOR SELECT USING (auth.uid() IS NOT NULL);

-- 2. Semua user login boleh INPUT penjualan (Kasir butuh ini)
CREATE POLICY "Public Insert Sales" ON sales FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Public Delete Sales" ON sales FOR DELETE USING (auth.uid() IS NOT NULL); -- Biar bisa hapus cart

-- 3. HANYA OWNER YANG BOLEH UBAH PRODUK (Tambah/Hapus Menu)
CREATE POLICY "Owner Manage Products" ON products FOR ALL 
USING (
  EXISTS (SELECT 1 FROM user_profiles WHERE user_id = auth.uid() AND role = 'owner')
);

-- 4. User bisa baca profil sendiri
CREATE POLICY "Read Own Profile" ON user_profiles FOR SELECT USING (auth.uid() = user_id);

-- SETUP SELESAI! 
-- Sekarang buat user 'admin@tokoku.com' di Authentication > Users
-- Password bebas (misal: admin123456)
-- User tersebut otomatis jadi OWNER dengan akses penuh!